AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for EC2 nano instance with Valkey installation'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select an existing VPC

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Select a subnet within the selected VPC

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access
    ConstraintDescription: Must be the name of an existing EC2 KeyPair

  MyIP:
    Description: Your IP address for security group access (x.x.x.x/32)
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/32

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic from MyIP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1  # Allows all traffic
          FromPort: -1    # All ports
          ToPort: -1      # All ports
          CidrIp: !Ref MyIP
      Tags:
        - Key: Name
          Value: Valkey-Server-SG

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      SecurityGroupIds: 
        - !Ref EC2SecurityGroup
      KeyName: !Ref KeyName
      ImageId: ami-0440d3b780d96b29d  # Amazon Linux 2 AMI in us-east-1
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          sudo yum install gcc jemalloc-devel openssl-devel tcl tcl-devel -y 
          wget https://github.com/valkey-io/valkey/archive/refs/tags/7.2.7.tar.gz 
          tar xvzf 7.2.7.tar.gz 
          cd valkey-7.2.7/ 
          make BUILD_TLS=yes install
      Tags:
        - Key: Name
          Value: Valkey Server

Outputs:
  InstanceId:
    Description: Instance ID of the newly created EC2 instance
    Value: !Ref EC2Instance

  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName

  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

  SSHCommand:
    Description: Command to SSH into the instance
    Value: !Sub "ssh -i ${KeyName}.pem ec2-user@${EC2Instance.PublicIp}"