AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Serverless ElastiCache Valkey'

Resources:
  ServerlessCache:
    Type: AWS::ElastiCache::ServerlessCache
    Properties:
      ServerlessCacheName: ec-valkey-serverless
      Engine: valkey
      CacheUsageLimits:
        DataStorage:
          Maximum: 1000  # Maximum storage in GB
        ECPU:
          Maximum: 100   # Maximum ECPU units
      DailySnapshotTime: '04:00'
      SnapshotRetentionLimit: 7
      Tags:
        - Key: Environment
          Value: Production

Outputs:
  ServerlessCacheId:
    Description: ID of the serverless cache
    Value: !Ref ServerlessCache
  
  ServerlessCacheEndpoint:
    Description: Endpoint for the serverless cache
    Value: !GetAtt ServerlessCache.EndpointAddress